### ISSUE TITLE
Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by joelazwar** [Jasper-Mui/me-check-links#10]
Hey I'm gonna add the feature to your program for lab 4 to ignore URL patterns like so

[https://github.com/Seneca-CDOT/topics-in-open-source-2020/wiki/lab-4#feature-ignore-url-patterns](https://github.com/Seneca-CDOT/topics-in-open-source-2020/wiki/lab-4#feature-ignore-url-patterns)

**Comment by joelazwar** [comment]
Hey Jasper, I've coded the ignore url feature on a new branch 'issue-10' Here's the link to my fork

[https://github.com/joelazwar/me-check-links.git](https://github.com/joelazwar/me-check-links.git)

Let me know if you have any feedback or if you decide to merge it

**Comment by Jasper-Mui** [comment]
I will have a look at it. Thanks for your contribution.

**Comment by Jasper-Mui** [comment]
I am getting an error when I am trying to use the new feature. Please see the picture below. 

![image](https://user-images.githubusercontent.com/58538645/96353837-c0790a80-109d-11eb-9abd-caf52f8e6e37.png)

**Comment by joelazwar** [comment]
hey jasper, I made a mistake and coded it so that the syntax is 
`mcl -i <html file> <ignore file>` 
I'm going to make changes right now. However could you check if the syntax above works? Thanks

**Comment by Jasper-Mui** [comment]
Yeah, that works. If you just switch the files it should be fine.

**Comment by joelazwar** [comment]
just pushed another commit that changed the above error. Let me know if it works. you should also be able to process multiple html files with the flag now as well

**Comment by Jasper-Mui** [comment]
I am not getting the expected output. I think the filter should be a regex as the match should match starting URL not just exact  match. Please see the requirements below.
![image](https://user-images.githubusercontent.com/58538645/96359677-803c7b00-10e3-11eb-9cc1-3ba736928508.png)

**Comment by joelazwar** [comment]
Hey Jasper, nice catch, you're right that is an error on my part. I've fixed the code again, this time much more thoroughly, sorry about that. Hopefully it should work as intended.

**Comment by Jasper-Mui** [comment]
It looks pretty good now. Only a small thing but the error message does not looks too good. 
![image](https://user-images.githubusercontent.com/58538645/96376319-3340bf00-114c-11eb-8e61-012974e36b57.png)
![image](https://user-images.githubusercontent.com/58538645/96376323-39cf3680-114c-11eb-8e4f-e9bc96792c13.png)

the test file just has a bad line but it is nice that it is handling it properly. Not a big deal though I like what you have done so far.

**Comment by joelazwar** [comment]
Hey Jasper, what's wrong specifically with the error message? Would you like me to fix it ? or is it fine to merge with your master branch? Let me know, thanks 👍

**Comment by Jasper-Mui** [comment]
Its just the at E:\my code\OSD600... it just looks a bit like an abnormal termination do you know where this is coming from? As we do see the Error: Invalid Ignore File which is great.

**Comment by joelazwar** [comment]
Hmmm if you mean the messages under the  "Invalid Ignore File" error, I threw an error on line 65 in main.js which terminates the program in the case of an invalid ignore file.

**Comment by Jasper-Mui** [comment]
Do you know if there is a way to terminate the program without the error messages below "Invalid Ignore File" error?

**Comment by joelazwar** [comment]
I just did some quick google searches and I coudn't seem to find an answer to eliminate the 'stack traces' as they call them. I think they just come with throwing errors. Right now I can't think of any other way to terminate the program

**Comment by Jasper-Mui** [comment]
Ok, I have merged your code. Thank you for your work and for following up.
